# -*- coding: utf-8 -*-
"""task3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/dharmarjunreddy/PRODIGY_DS_03/blob/main/task3.ipynb
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import plotly.express as plx
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

# %matplotlib inline

file_1 = pd.read_csv('/content/bank-full.csv',sep= ';')

file_1.head(20)

file_2=pd.read_csv("bank-additional-full.csv",sep=";")

file_2.head(20)

All_Data = pd.concat([file_1, file_2], ignore_index=True)
All_Data

count_values = {}
for col in All_Data.columns:
    count_values[col] = len(All_Data[col].unique())

for col, count in count_values.items():
    print(col, count)

All_Data.isnull().sum()

data_1 = All_Data.dropna(axis=1)
data_1

data_1.isnull().sum()

plx.pie(data_1,names="job")

grouped = data_1.groupby('default').size().reset_index(name='num_employees')
plt.bar(grouped['default'], grouped['num_employees'], color=['blue', 'green'])
plt.xlabel('Default Status')
plt.ylabel('Number of Employees')
plt.title('Total Number of Employees by Default Status')
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()

